### ISSUE TITLE
WHITEHATgrandprix2018 pwn03 nice writeup. Thank you!

### ISSUE THREAD

**Issue by LePhamThienHongAn** [perfectblue/ctf-writeups#2]
https://github.com/perfectblue/ctf-writeups/blob/master/whitehat-grandprix-2018/pwn03_onehit.md
Hi i am author of this chal :D
You dont have to guess ASLR base if you can run system(null); (by answer "N0" when it ask "wanna ls -al")
Because it will leave the address of instuction after CALL do_system on the stack. I want to prevent you guess ASLR base by using AntiSPAM Machine but ... apparently it doesn't work :(

**Comment by ret2jazzy** [comment]
heh, guessing only 12 bits wasn't that bad ;)

**Comment by LePhamThienHongAn** [comment]
but you have to solve a hash to try one time ... next time i will inc the difficult of solving hash :(

**Comment by ret2jazzy** [comment]
We actually wrote a C program which solved the hash in no time.
