### ISSUE TITLE
keeping crash after unpacking with upx3.94w

### ISSUE THREAD

**Issue by ruleil** [perfectblue/ctf-writeups#3]
Hi 

I'm facing crash issues after unpack WH2018.exe with upx394w\upx.exe. The unpacked file are keeping crash. Could you give me some suggestion? Thanks.

I have attached the file I'm trying to unpack. 

[WH2018_pe_fixed2.zip](https://github.com/perfectblue/ctf-writeups/files/2364359/WH2018_pe_fixed2.zip)

**Comment by stong** [comment]
Hi! Thanks for reading my writeup.

I compared your version with the [one from the repo](https://github.com/perfectblue/ctf-writeups/blob/master/whitehat-grandprix-2018/rev04/cock.exe). I think your imports data directory size is wrong.

![image](https://user-images.githubusercontent.com/14918218/45269821-1eb87580-b462-11e8-812b-0fd5d96f8ea5.png)

vs

![image](https://user-images.githubusercontent.com/14918218/45269822-21b36600-b462-11e8-9fca-4a02768dd0c8.png)

(correct one)

Hope that helps.

**Comment by ruleil** [comment]
Hi RollSafe

Thanks for your information. This is a pretty good write up. I'm new for CTF and I learned a lot from your write up.

I followed your write up again, and found that the imported directory size is 3B4 after fixing PE structure. So do we need to modify it manually? I didn't see this step within your write up.

Thanks

**Comment by stong** [comment]
Hi,

I took a lot of steps to fix the binary, I probably simply forgot about it.
3b4 is a huge imports size so I must have patched it and neglected to
include it in the writeup.

**Comment by ruleil** [comment]
Hi,

Thanks a lot. You are really good at CTF and documentation.

**Comment by ruleil** [comment]
Hi Sir

Find a solution that can fix the crash issue from this write up: https://github.com/p4-team/ctf/blob/master/2018-08-18-whitehat/re04/README.md 

The binary is crashing because of memory misaligment issues, to solve that we have to turn on the Relocation information is stripped from the file bit:

![image](https://user-images.githubusercontent.com/35195892/45287676-6ea74300-b51b-11e8-8904-dadc7aab9d02.png)
