### ISSUE TITLE
blazeme:  kallsyms 

### ISSUE THREAD

**Issue by robgalvan** [perfectblue/ctf-writeups#4]
Hey cool write-up! I was wondering how you were able to get kernel addresses ```commit_creds(prepare_kernel_cred(0));``` without root on the box?

**Comment by stong** [comment]
KASLR was off since its QEMU, you could get it from kallsyms which was
enabled or just from vmlinuz

Best.

**Comment by robgalvan** [comment]
Right but you are not root so you can’t print out /proc/kallsyms ?

**Comment by stong** [comment]
It’s been a long time since I did the challenge, but I believe it was
enabled for non root users to access it.

**Comment by robgalvan** [comment]
Gotcha gotcha no worries I’ll figure it out. Thanks!
