### ISSUE TITLE
How to run KVM file

### ISSUE THREAD

**Issue by VictorAlonsoCM** [perfectblue/ctf-writeups#5]
Hello, sorry for this issue but I have a problem with the kvm file.
The problem that I have is that I don't know how to run the file. When I  try to run it my Kali says that 
"open /dev/kvm: No such file or directory" and I don't know what to do, I followed many tutorials about how to run this kind of binaries but none of these work for me.
Can you help me please?

**Comment by stong** [comment]
Either your processor doesn’t support virtualization, or it’s disabled in
BIOS.

Show `cat /proc/cpuid` please?

**Comment by VictorAlonsoCM** [comment]
``cat: /proc/cpuid: No such file or directory`` this the output that I got.

I am using VMware with "Kali Linux 64 bit VMware VM", probably this is why it can't run this kind of file.
I'm going to install a full version of Kali and then I come back with the `cat /proc/cpuid` output.

**Comment by stong** [comment]
Just use ubuntu

**Comment by VictorAlonsoCM** [comment]
My ubuntu is loading I'll send the output when it'll be ready beacuse I had a similar issue trying to running the file

**Comment by VictorAlonsoCM** [comment]
My ubuntu outputs the same ``cat: /proc/cpuid: No such file or director`` using ``cat /proc/cpuid``

**Comment by stong** [comment]
It’s /proc/cpuinfo, my bad.

**Comment by VictorAlonsoCM** [comment]
This is what I got:

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 61
model name	: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
stepping	: 4
microcode	: 0x2a
cpu MHz		: 2394.455
cache size	: 4096 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 20
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid rdseed adx smap xsaveopt dtherm ida arat pln pts
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips	: 4788.91
clflush size	: 64
cache_alignment	: 64
address sizes	: 42 bits physical, 48 bits virtual
power management:

**Comment by stong** [comment]
Your cpu should support virtualization

Ensure kvm is installed and configured properly. Check the instructions here
https://www.linux-kvm.org/page/FAQ

**Comment by VictorAlonsoCM** [comment]
Thanks I'll do that and then I come back thanks.
