### ISSUE TITLE
googleCTF 2020 / tracing: Which DC?

### ISSUE THREAD

**Issue by is8ac** [perfectblue/ctf-writeups#9]
I rented a VPC in all three DCs in Amsterdam, and got ~1ms latency with significant fluctuation. I likely could have obtained a sufficiently crisp signal from one of them, but it would have required averaging over far more then the 10 attempts which you used.

Which DC did you use, and what latency did you get?

**Comment by stong** [comment]
I will ask @sampritipanda

**Comment by stong** [comment]
We used Belgium DC and the latency is like 0.5

**Comment by MrHide23** [comment]
I think you got confused about your email Bro, I don't know what you're
talking about. Apparently you belong to perfectblue, but I have not
participated in any CTF at a level as high as yours
